### ISSUE TITLE
Add a welcome message

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST336FINAL-PROJECT#10]
Would it be ok if I added a welcome message to the main store page?

![suggest](https://user-images.githubusercontent.com/22785028/43692901-eb4f9cca-98df-11e8-97f1-facf495fbaf0.jpg)

**Comment by Mcghee-Jake** [comment]
I have a welcome message added in my local files. I just haven't merged it with the repo yet. It looks like this

![capture](https://user-images.githubusercontent.com/33072387/43693038-acddbf02-98e0-11e8-9b21-8a66fb94e7fd.JPG)

**Comment by p12345vls** [comment]
Good

**Comment by mdoussias** [comment]
Cool.  Looks great guys.

**Comment by mdoussias** [comment]
Also note, I made a footer.    See below:
https://github.com/team-makeSmart/CST336FINAL-PROJECT/issues/3

**Comment by Mcghee-Jake** [comment]
added in with my most recent pull request
