### ISSUE TITLE
Two db connections 

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST336FINAL-PROJECT#18]
We have three dbConnection.php files

CST336FINAL-PROJECT/dbConnection.php
CST336FINAL-PROJECT/php/dbConnection.php
CST336FINAL-PROJECT/admin/dbConnection.php

Do we need all three?

**Comment by p12345vls** [comment]
I know I can delete it later when I will complete  error checking and post pull request

**Comment by mdoussias** [comment]
I don't want to cause last minute bugs... 
I think we should remove, only with time permitting.

**Comment by p12345vls** [comment]
I didnt remove it

**Comment by mdoussias** [comment]
No need to make a change last minute that may cause bugs.  Closing this issue.
