### ISSUE TITLE
Purchases

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST336FINAL-PROJECT#22]
If a CUSTOMER  makes two purchases with the same email address, the program will crash.

We can do one of two things:

- [ ] Change the SQL database table creation file so that the address field is not indexed.  Currently the customer.address field is set to be UNIQUE.  This will allow the program to have multiple users with the same address.  Nothing unique will identify the user except the user id

- [ ] Fix the purchase program site to check address and then check if it matches any previous entries, and return an error if the name fields don't match.

- [ ] Change the address field to a credit card field.... But then we'd have to change all references in the store side and the SQL files and the ER diagram.  

- [ ] Something I haven't thought of

**Comment by Mcghee-Jake** [comment]
Sorry I don't have a enough time today to fix this. But I don't imagine that we would get docked for this. But if someone wants to take care of it then I think just removing the UNIUQE field would be good enough. Just let us know if you do that so that we can all update our phpmyadmin database

**Comment by mdoussias** [comment]
Did not change UNIQUE because I am causing bug crashes when I changed the SQL file.  Don't want to cause a worse bug so not going to implement.  I'll still keep trying and let you all know if I find a solution, but given the time.... probably best to let this one slide.
