### ISSUE TITLE
More descriptive placeholder on checkout.php

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST336FINAL-PROJECT#23]
I would put this code in as a pull request, but I know Jake is working on a separate file.  
I think for clarity, it might read better to have a more descriptive placeholder in the customer.address field of the checkout.php file 

![screen shot 2018-08-06 at 8 57 55 pm](https://user-images.githubusercontent.com/22785028/43753816-73d6fed0-99bc-11e8-86b8-7216544cef7b.png)
![example](https://user-images.githubusercontent.com/22785028/43753819-75d15a14-99bc-11e8-8386-8702d433fd31.jpg)

**Comment by Mcghee-Jake** [comment]
I added this in as part of my most recent pull request
