### ISSUE TITLE
Admin Page Update and Add records issue

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST336FINAL-PROJECT#24]
When updating records or adding records, if a person puts something other than an integer in the priceCent and priceDollar fields, then the value entered will result in 0 being added.  

Shouldn't this prompt an error message.  Not sure how to check for integer values.  Looking into it.  Not sure if worth it to change at this point.  Thoughts?

**Comment by p12345vls** [comment]
Are you running the new version?

**Comment by p12345vls** [comment]
https://cst-336-project.herokuapp.com/admin/addProduct.php?plantName=&plantDesc=&priceDollar=&priceCent=w&imgLink=&submitProduct=Add+Product

**Comment by p12345vls** [comment]
![screen shot 2018-08-06 at 10 58 34 pm](https://user-images.githubusercontent.com/32381448/43757069-661e7452-99cc-11e8-82b0-0cd85335c495.png)

**Comment by mdoussias** [comment]
I think I was but I will double-check right now.

**Comment by mdoussias** [comment]
My bad, You are right.  I pulled the local repository again.  Sorry for the concern.  

Everything works great.
