### ISSUE TITLE
DISCUSSION footer.php?

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST336FINAL-PROJECT#3]
Should we add a footer file to include in all pages... 

Below is what I'd add as a footer.php file to include in all pages.  Note that if you copy and paste below, it should show up better in your IDE:

    **<footer id='footerId'>
          <hr>
			     <p>
			       CSUMB CST 336. 2018&copy; Team Makesmart Team Final Project <br />
			       <strong>Disclaimer:</strong><br /> 
			       The information in this webpage is fictitious. <br />
    			   This site is for academic purposes only. <br />
			       All plant description and images are from research 
                                retrieved August 5th, 2015 from: <br />
		<a href='https://en.wikipedia.org/wiki/List_of_poisonous_plants'>
                  https://en.wikipedia.org/wiki/List_of_poisonous_plants</a>
</footer>**

**Comment by mdoussias** [comment]
I can add this easily if everyone is agreed.  I'll make the text small for the footer.

**Comment by p12345vls** [comment]
Agree

**Comment by mdoussias** [comment]
A footer can now be put in any page just by including the following at the bottom of the page:

![screen shot 2018-08-05 at 8 11 36 pm](https://user-images.githubusercontent.com/22785028/43695164-c91e4c3a-98eb-11e8-8ec9-5a1e71202c15.png)

**Comment by Mcghee-Jake** [comment]
If you want to add this in I'm cool with it. I'm cool with skipping it too, up to you.

**Comment by mdoussias** [comment]
Footer was added to the home page and to the opening admin pages.
