### ISSUE TITLE
error message on admin login could be centered

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST336FINAL-PROJECT#9]
I can fix this, but I'm just recording this here.
It can be done last thing, because it won't doc points.

![screen shot 2018-08-05 at 6 38 21 pm](https://user-images.githubusercontent.com/22785028/43692742-d3d7708c-98de-11e8-8028-ad093fba2c5e.png)

**Comment by p12345vls** [comment]
I ll fix it
